config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #get '/calculadora/:name', to: 'calculator#home', as: 'home'
  get '/calculadora/:first_number/:second_number', to: 'calculator#home', as: 'home'
  get '/calculadora/:first_number/:second_number/soma', to: 'calculator#sum_result', as: 'sum_numbers'
  get '/calculadora/:first_number/:second_number/subtracao', to: 'calculator#subtract_result', as: 'subtract_numbers'
  get '/calculadora/:first_number/:second_number/multiplicacao', to: 'calculator#multiply_result', as: 'multiply_numbers'
  get '/calculadora/:first_number/:second_number/divisao', to: 'calculator#divide_result', as: 'divide_numbers'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/calculator_controller.rb
class CalculatorController < ApplicationController
    def home
        @first_number = params[:first_number].to_i
        @second_number = params[:second_number].to_i
    end

    def sum_result
        @result = params[:first_number].to_i + params[:second_number].to_i
    end

    def subtract_result
        @result = params[:first_number].to_i - params[:second_number].to_i
    end

    def multiply_result
        @result = params[:first_number].to_i * params[:second_number].to_i
    end

    def divide_result
        @result = params[:first_number].to_f / params[:second_number].to_f
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/calculator/divide_result.html.erb
<p>Resultado: <%= @result %></p>

app/views/calculator/home.html.erb
<div class="container">
    <div class="items">
        <h1>Calculadora</h1>
        <div class="actions">
            <%= link_to "Somar", sum_numbers_path() %>
            <%= link_to "Subtrair", subtract_numbers_path() %>
            <%= link_to "Multiplicar", multiply_numbers_path() %>
            <%= link_to "Dividir", divide_numbers_path() %>
        </div>
    </div>
</div>

app/views/calculator/multiply_result.html.erb
<p>Resultado: <%= @result %></p>

app/views/calculator/subtract_result.html.erb
<p>Resultado: <%= @result %></p>

app/views/calculator/sum_result.html.erb
<p>Resultado: <%= @result %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Calculadora</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'reset', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag    'home', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag asset_path('calculator.svg') %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>